[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Make `cargo run` start a GDB session
runner = "gdb-multiarch -q -x openocd.gdb"

[build]
# Default compilation target is Cortex-M4 on the STM32G474 MCU
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)
